version: '2.0'  # if no version is specified then v1 is assumed. Recommend v2 minimum

services: 
  drupal: # this is also DNS name inside network
    image: drupal:8.8.2 # Optional if you use build:
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes: